# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Try to Build a GitHub Blog
url: http://xjmwx4.github.io
feed: /atom.xml
author_info: <a href="http://litaotao.github.io/">xujia64</a>

myblog:
  gavatar: images/2.jpg
  gpname: xujia
  linkedin: http://www.linkedin.com/in/xjmwx4
  github: https://github.com/xjmwx4
  email: mailto:xjmwx4@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
